command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: SERVING_ENDPOINT
    value: databricks-claude-sonnet-4-6
  - name: CATALOG
    value: sarbanimaiti_catalog
  - name: SCHEMA
    value: agent_eval
  - name: VS_ENDPOINT
    value: one-env-shared-endpoint-11
